### ISSUE TITLE
Deploying new "empty" on vercel with errors

### ISSUE THREAD

**Issue by inpec-org** [leerob/leerob.io#494]
Estou com dificuldades para publicar na Vercel.
Não sou programador. Não falo inglês, desculpe, mas acredito que tradutor vá ajudar.

[10:01:25.942] Cloning github.com/inpec-org/site-org (Branch: main, Commit: 1a68ebb)
[10:01:29.092] Cloning completed: 3.150s
[10:01:29.539] Installing build runtime...
[10:01:31.530] Build runtime installed: 1.990s
[10:01:32.206] Looking up build cache...
[10:01:32.448] Build Cache not found
[10:01:32.716] Installing dependencies...
[10:01:32.716] Detected `pnpm-lock.yaml` generated by pnpm 7...
[10:01:33.242] Lockfile is up-to-date, resolution step is skipped
[10:01:33.278] Progress: resolved 1, reused 0, downloaded 0, added 0
[10:01:33.433] Packages: +599
[10:01:33.434] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[10:01:33.931] Packages are hard linked from the content-addressable store to the virtual store.
[10:01:33.931]   Content-addressable store is at: /vercel/.local/share/pnpm/store/v3
[10:01:33.931]   Virtual store is at:             node_modules/.pnpm
[10:01:34.281] Progress: resolved 599, reused 0, downloaded 21, added 16
[10:01:35.282] Progress: resolved 599, reused 0, downloaded 57, added 51
[10:01:36.281] Progress: resolved 599, reused 0, downloaded 126, added 120
[10:01:37.282] Progress: resolved 599, reused 0, downloaded 235, added 233
[10:01:38.284] Progress: resolved 599, reused 0, downloaded 293, added 293
[10:01:39.287] Progress: resolved 599, reused 0, downloaded 328, added 326
[10:01:40.287] Progress: resolved 599, reused 0, downloaded 366, added 365
[10:01:41.289] Progress: resolved 599, reused 0, downloaded 423, added 418
[10:01:42.303] Progress: resolved 599, reused 0, downloaded 490, added 489
[10:01:43.311] Progress: resolved 599, reused 0, downloaded 525, added 522
[10:01:44.319] Progress: resolved 599, reused 0, downloaded 573, added 570
[10:01:45.322] Progress: resolved 599, reused 0, downloaded 590, added 590
[10:01:46.331] Progress: resolved 599, reused 0, downloaded 592, added 591
[10:01:47.330] Progress: resolved 599, reused 0, downloaded 595, added 595
[10:01:48.333] Progress: resolved 599, reused 0, downloaded 599, added 599, done
[10:01:48.679] .../node_modules/@prisma/engines postinstall$ node download/index.js
[10:01:48.680] .../node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
[10:01:48.711] .../node_modules/protobufjs postinstall$ node scripts/postinstall
[10:01:48.764] .../node_modules/core-js-pure postinstall: Done
[10:01:48.845] .../node_modules/protobufjs postinstall: Done
[10:01:51.005] .../node_modules/@prisma/engines postinstall: Done
[10:01:51.532] .../esbuild@0.14.42/node_modules/esbuild postinstall$ node install.js
[10:01:51.615] .../prisma@3.14.0/node_modules/prisma preinstall$ node scripts/preinstall-entry.js
[10:01:51.636] .../esbuild@0.14.42/node_modules/esbuild postinstall: Done
[10:01:51.702] .../prisma@3.14.0/node_modules/prisma preinstall: Done
[10:01:51.702] .../prisma@3.14.0/node_modules/prisma install$ node scripts/install-entry.js
[10:01:51.759] .../prisma@3.14.0/node_modules/prisma install: Done
[10:01:51.863] .../node_modules/@prisma/client postinstall$ node scripts/postinstall.js
[10:01:53.173] .../node_modules/@prisma/client postinstall: Prisma schema loaded from prisma/schema.prisma
[10:01:55.360] .../node_modules/@prisma/client postinstall: ✔ Generated Prisma Client (3.15.0 | library) to ./node_modules/.pnpm/@prisma+client@3.15.0_prisma@3.14.0/node_modules/@prisma/client in 356ms
[10:01:55.361] .../node_modules/@prisma/client postinstall: You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[10:01:55.361] .../node_modules/@prisma/client postinstall: ```
[10:01:55.361] .../node_modules/@prisma/client postinstall: import { PrismaClient } from '@prisma/client'
[10:01:55.362] .../node_modules/@prisma/client postinstall: const prisma = new PrismaClient()
[10:01:55.362] .../node_modules/@prisma/client postinstall: ```
[10:01:55.362] .../node_modules/@prisma/client postinstall: warn Versions of prisma@3.14.0 and @prisma/client@3.15.0 don't match.
[10:01:55.362] .../node_modules/@prisma/client postinstall: This might lead to unexpected behavior.
[10:01:55.362] .../node_modules/@prisma/client postinstall: Please make sure they have the same version.
[10:01:55.463] .../node_modules/@prisma/client postinstall: Done
[10:01:55.593] .../node_modules/contentlayer postinstall$ node ./bin/cli.cjs postinstall || echo 'No Contentlayer build found.'
[10:01:57.825] .../node_modules/contentlayer postinstall: Done
[10:01:58.034] 
[10:01:58.034] dependencies:
[10:01:58.034] + @prisma/client 3.15.0
[10:01:58.034] + @tailwindcss/typography 0.5.2
[10:01:58.034] + classnames 2.3.1
[10:01:58.034] + contentlayer 0.2.5
[10:01:58.034] + date-fns 2.28.0
[10:01:58.034] + googleapis 48.0.0
[10:01:58.034] + motion 10.10.0
[10:01:58.035] + next 12.1.7-canary.32
[10:01:58.035] + next-auth 4.3.3
[10:01:58.035] + next-contentlayer 0.2.5
[10:01:58.035] + preact 10.7.3
[10:01:58.035] + react 17.0.2
[10:01:58.035] + react-dom 17.0.2
[10:01:58.035] + swr 1.3.0
[10:01:58.035] + tailwindcss 3.0.24
[10:01:58.035] + use-delayed-render 0.0.7
[10:01:58.035] 
[10:01:58.035] devDependencies:
[10:01:58.035] + @types/react 18.0.12
[10:01:58.035] + autoprefixer 10.4.7
[10:01:58.035] + eslint 8.15.0
[10:01:58.035] + eslint-config-next 12.1.6
[10:01:58.035] + globby 13.1.1
[10:01:58.036] + postcss 8.4.14
[10:01:58.036] + prettier 2.6.2
[10:01:58.036] + prisma 3.14.0
[10:01:58.036] + reading-time 1.5.0
[10:01:58.036] + rehype 12.0.1
[10:01:58.036] + rehype-autolink-headings 6.1.1
[10:01:58.036] + rehype-code-titles 1.0.3
[10:01:58.036] + rehype-prism-plus 1.4.0
[10:01:58.036] + rehype-slug 5.0.1
[10:01:58.036] + remark-gfm 3.0.1
[10:01:58.036] + rss 1.2.2
[10:01:58.036] + typescript 4.7.3
[10:01:58.036] 
[10:01:58.056] Detected Next.js version: 12.1.7-canary.32
[10:01:58.094] Detected `pnpm-lock.yaml` generated by pnpm 7...
[10:01:58.095] Running "pnpm run build"
[10:01:58.539] 
[10:01:58.540] > @ build /vercel/path0
[10:01:58.540] > next build
[10:01:58.540] 
[10:01:58.959] warn  - You have enabled experimental feature(s).
[10:01:58.959] warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
[10:01:58.960] 
[10:01:58.960] warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
[10:02:05.825] Generated 90 documents in .contentlayer
[10:02:05.846] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[10:02:05.847] This information is used to shape Next.js' roadmap and prioritize features.
[10:02:05.847] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[10:02:05.847] https://nextjs.org/telemetry
[10:02:05.847] 
[10:02:05.976] info  - Linting and checking validity of types...
[10:02:19.357] Failed to compile.
[10:02:19.357] 
[10:02:19.358] ./pages/blog.tsx:6:22
[10:02:19.358] Type error: Cannot find module '@contentlayer/utils' or its corresponding type declarations.
[10:02:19.358] 
[10:02:19.358] [0m [90m 4 | [39m[36mimport[39m [33mBlogPost[39m [36mfrom[39m [32m'components/BlogPost'[39m[33m;[39m[0m
[10:02:19.358] [0m [90m 5 | [39m[36mimport[39m { [33mInferGetStaticPropsType[39m } [36mfrom[39m [32m'next'[39m[33m;[39m[0m
[10:02:19.359] [0m[31m[1m>[22m[39m[90m 6 | [39m[36mimport[39m { pick } [36mfrom[39m [32m'@contentlayer/utils'[39m[33m;[39m[0m
[10:02:19.359] [0m [90m   | [39m                     [31m[1m^[22m[39m[0m
[10:02:19.359] [0m [90m 7 | [39m[36mimport[39m { allBlogs } [36mfrom[39m [32m'contentlayer/generated'[39m[33m;[39m[0m
[10:02:19.359] [0m [90m 8 | [39m[0m
[10:02:19.419] 
[10:02:19.419] > Build error occurred
[10:02:19.421] Error: Call retries were exceeded
[10:02:19.421]     at ChildProcessWorker.initialize (/vercel/path0/node_modules/.pnpm/next@12.1.7-canary.32_sfoxds7t5ydpegc3knd667wn6m/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
[10:02:19.421]     at ChildProcessWorker._onExit (/vercel/path0/node_modules/.pnpm/next@12.1.7-canary.32_sfoxds7t5ydpegc3knd667wn6m/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
[10:02:19.422]     at ChildProcess.emit (node:events:520:28)
[10:02:19.422]     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
[10:02:19.422]   type: 'WorkerError'
[10:02:19.422] }
[10:02:19.441]  ELIFECYCLE  Command failed with exit code 1.
[10:02:19.453] Error: Command "pnpm run build" exited with 1

**Comment by leerob** [comment]
Fixed!
