### ISSUE TITLE
Blog rendering error 

### ISSUE THREAD

**Issue by uvpro** [leerob/leerob.io#545]
I cloned the original repo and I have changed all the env. with my keys. But when I try to access the page of an article published with  sanity studio I get the following error:

```
error - lib\mdx.ts (30:30) @ mdxToHtml
error - TypeError: Cannot read properties of null (reading 'match')
    at mdxToHtml (webpack-internal:///./lib/mdx.ts:47:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getStaticProps (webpack-internal:///./pages/blog/[slug].tsx:79:48)
    at async Object.renderToHTML (C:\Users\Ulises\Documents\GitHub\portfolio\node_modules\next\dist\server\render.js:390:20)
    at async doRender (C:\Users\Ulises\Documents\GitHub\portfolio\node_modules\next\dist\server\base-server.js:642:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (C:\Users\Ulises\Documents\GitHub\portfolio\node_modules\next\dist\server\base-server.js:747:28)
    at async C:\Users\Ulises\Documents\GitHub\portfolio\node_modules\next\dist\server\response-cache\index.js:80:36 {
  page: '/blog/[slug]'
}
  28 |   });
  29 | 
> 30 |   const tweetMatches = source.match(/<StaticTweet\sid="[0-9]+"\s\/>/g);
     |                              ^
  31 |   const tweetIDs = tweetMatches?.map((tweet) => tweet.match(/[0-9]+/g)[0]);
  32 | 
  33 |   return {
```

At first I thought it was a problem with the twitter API, but I managed to solve it and see the page tweets.tsx

Then I thought it could be a revalidation problem, but I also tried 4 different webhooks in Sanity (I have no idea what the filter and project codes should be) but the error remains. 

You will realize that I am a novice programmer, actually I am a designer, basically I find the answers on the internet but this was impossible for me.

I've been breaking my mind for 2 weeks with this, I had to resort to your wonderful knowledge @leerob  🙏

**Comment by basmango** [comment]
this is because the schema leerob is using is not the same that sanity auto generates with the blog template,

**Comment by uvpro** [comment]
> this is because the schema leerob is using is not the same that sanity auto generates with the blog template,

Thanks for the answer, I'll be changing the scheme and giving updates.

**Comment by leerob** [comment]
Thank you @basmango!
