### ISSUE TITLE
deploying new empty template shows error

### ISSUE THREAD

**Issue by yoomiraa** [leerob/leerob.io#637]
```
[Error: ENOENT: no such file or directory, stat '/vercel/path0/public/images'] {
--
12:07:39.213 | errno: -2,
12:07:39.213 | code: 'ENOENT',
12:07:39.213 | syscall: 'stat',
12:07:39.213 | path: '/vercel/path0/public/images'
12:07:39.213 | }
12:07:39.214 |  
12:07:39.214 | Node.js v18.16.1
12:07:39.224 | ELIFECYCLE  Command failed with exit code 1.
12:07:39.249 | Error: Command "pnpm run build" exited with 1

```

**Comment by yoomiraa** [comment]
the issue aboved is solved by adding a new folder 'image' inside public folder, but then new errors showed up

[12:14:55.340] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[12:14:55.383] Cloning github.com/yoomiraa/zstvn (Branch: main, Commit: aefff16)
[12:14:59.050] Cloning completed: 3.667s
[12:15:04.990] Restored build cache
[12:15:05.021] Running "vercel build"
[12:15:05.538] Vercel CLI 31.0.3
[12:15:05.822] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8...
[12:15:05.844] Installing dependencies...
[12:15:06.429] Lockfile is up to date, resolution step is skipped
[12:15:06.530] Progress: resolved 1, reused 0, downloaded 0, added 0
[12:15:06.630] Packages: +54 -49
[12:15:06.631] +++++++++++++++++++++++++++++++++++++++++---------------------------------------
[12:15:07.538] Progress: resolved 54, reused 0, downloaded 7, added 5
[12:15:08.551] Progress: resolved 54, reused 0, downloaded 33, added 27
[12:15:09.551] Progress: resolved 54, reused 0, downloaded 53, added 53
[12:15:10.831] Progress: resolved 54, reused 0, downloaded 54, added 53
[12:15:11.977] Progress: resolved 54, reused 0, downloaded 54, added 54, done
[12:15:12.075] .../node_modules/contentlayer postinstall$ node ./bin/cli.cjs postinstall || echo 'No Contentlayer build found.'
[12:15:13.633] .../node_modules/contentlayer postinstall: Done
[12:15:13.722] 
[12:15:13.733] Done in 7.8s
[12:15:13.757] Detected Next.js version: 13.4.8-canary.5
[12:15:13.765] Running "pnpm run build"
[12:15:14.268] 
[12:15:14.268] > @ build /vercel/path0
[12:15:14.268] > npm run setup && next build
[12:15:14.268] 
[12:15:14.658] 
[12:15:14.658] > setup
[12:15:14.659] > node ./lib/setup.mjs
[12:15:14.659] 
[12:15:15.118] - info Loaded env from /vercel/path0/.env
[12:15:15.248] - warn You have enabled experimental feature (serverActions) in next.config.js.
[12:15:15.249] - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[12:15:15.249] 
[12:15:15.339] - info Creating an optimized production build...
[12:15:18.321] Generated 1 documents in .contentlayer
[12:15:53.145] - warn Compiled with warnings
[12:15:53.146] 
[12:15:53.146] ./node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/node.js
[12:15:53.146] Module not found: Can't resolve 'supports-color' in '/vercel/path0/node_modules/.pnpm/debug@4.3.4/node_modules/debug/src'
[12:15:53.146] 
[12:15:53.146] Import trace for requested module:
[12:15:53.147] ./node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/node.js
[12:15:53.147] ./node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/index.js
[12:15:53.147] ./node_modules/.pnpm/https-proxy-agent@5.0.1/node_modules/https-proxy-agent/dist/agent.js
[12:15:53.147] ./node_modules/.pnpm/https-proxy-agent@5.0.1/node_modules/https-proxy-agent/dist/index.js
[12:15:53.147] ./node_modules/.pnpm/gaxios@5.1.2/node_modules/gaxios/build/src/gaxios.js
[12:15:53.147] ./node_modules/.pnpm/gaxios@5.1.2/node_modules/gaxios/build/src/index.js
[12:15:53.147] ./node_modules/.pnpm/googleapis-common@6.0.4/node_modules/googleapis-common/build/src/index.js
[12:15:53.147] ./node_modules/.pnpm/googleapis@118.0.0/node_modules/googleapis/build/src/index.js
[12:15:53.147] ./lib/metrics.tsx
[12:15:53.147] ./app/blog/page.tsx
[12:15:53.147] 
[12:15:53.147] ./node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib/index.js
[12:15:53.147] Module not found: Can't resolve 'encoding' in '/vercel/path0/node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib'
[12:15:53.148] 
[12:15:53.148] Import trace for requested module:
[12:15:53.148] ./node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib/index.js
[12:15:53.149] ./node_modules/.pnpm/gaxios@5.1.2/node_modules/gaxios/build/src/gaxios.js
[12:15:53.149] ./node_modules/.pnpm/gaxios@5.1.2/node_modules/gaxios/build/src/index.js
[12:15:53.149] ./node_modules/.pnpm/googleapis-common@6.0.4/node_modules/googleapis-common/build/src/index.js
[12:15:53.156] ./node_modules/.pnpm/googleapis@118.0.0/node_modules/googleapis/build/src/index.js
[12:15:53.156] ./lib/metrics.tsx
[12:15:53.156] ./app/blog/page.tsx
[12:15:53.158] 
[12:15:53.160] - info Linting and checking validity of types...
[12:16:07.182] - info Collecting page data...
[12:16:07.790] unhandledRejection Error: Cannot find module '../../next@13.4.8-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/constants.js'
[12:16:07.790] Require stack:
[12:16:07.790] - /vercel/path0/.next/server/pages/_document.js
[12:16:07.790] - /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js
[12:16:07.792] - /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js
[12:16:07.792] - /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js
[12:16:07.792] - /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/worker.js
[12:16:07.792] - /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js
[12:16:07.792]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[12:16:07.792]     at /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:189:36
[12:16:07.792]     at Module._load (node:internal/modules/cjs/loader:922:27)
[12:16:07.792]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[12:16:07.792]     at require (node:internal/modules/cjs/helpers:110:18)
[12:16:07.793]     at 85511 (/vercel/path0/.next/server/pages/_document.js:32:18)
[12:16:07.793]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[12:16:07.793]     at 83520 (/vercel/path0/.next/server/chunks/520.js:41:20)
[12:16:07.793]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[12:16:07.793]     at __webpack_exec__ (/vercel/path0/.next/server/pages/_document.js:63:39) {
[12:16:07.793]   type: 'Error',
[12:16:07.793]   code: 'MODULE_NOT_FOUND',
[12:16:07.793]   requireStack: [
[12:16:07.793]     '/vercel/path0/.next/server/pages/_document.js',
[12:16:07.793]     '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js',
[12:16:07.793]     '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js',
[12:16:07.793]     '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js',
[12:16:07.793]     '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/worker.js',
[12:16:07.794]     '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js'
[12:16:07.794]   ]
[12:16:07.794] }
[12:16:07.979]  ELIFECYCLE  Command failed with exit code 1.
[12:16:08.026] Error: Command "pnpm run build" exited with 1

**Comment by yoomiraa** [comment]
fixed by changing building command to pnpm dev, stucks at building progress

[12:32:36.330] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[12:32:36.375] Cloning github.com/yoomiraa/zstvn (Branch: main, Commit: 8b180b4)
[12:32:37.784] Cloning completed: 1.409s
[12:32:42.556] Restored build cache
[12:32:42.588] Running "vercel build"
[12:32:43.089] Vercel CLI 31.0.3
[12:32:43.354] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8...
[12:32:43.379] Installing dependencies...
[12:32:43.942] Lockfile is up to date, resolution step is skipped
[12:32:44.038] Progress: resolved 1, reused 0, downloaded 0, added 0
[12:32:44.131] Packages: +54 -49
[12:32:44.132] +++++++++++++++++++++++++++++++++++++++++---------------------------------------
[12:32:45.039] Progress: resolved 54, reused 0, downloaded 10, added 6
[12:32:46.039] Progress: resolved 54, reused 0, downloaded 36, added 28
[12:32:47.039] Progress: resolved 54, reused 0, downloaded 53, added 53
[12:32:48.309] Progress: resolved 54, reused 0, downloaded 54, added 53
[12:32:49.506] Progress: resolved 54, reused 0, downloaded 54, added 54, done
[12:32:49.520] .../node_modules/contentlayer postinstall$ node ./bin/cli.cjs postinstall || echo 'No Contentlayer build found.'
[12:32:51.087] .../node_modules/contentlayer postinstall: Done
[12:32:51.179] 
[12:32:51.191] Done in 7.7s
[12:32:51.217] Detected Next.js version: 13.4.8-canary.5
[12:32:51.217] Running "pnpm dev"
[12:32:51.722] 
[12:32:51.723] > @ dev /vercel/path0
[12:32:51.723] > next dev
[12:32:51.723] 
[12:32:51.792] - warn You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
[12:32:52.075] - ready started server on 0.0.0.0:3000, url: http://localhost:3000
[12:32:52.242] - [36minfo[39m Loaded env from /vercel/path0/.env
[12:32:52.373] - [33mwarn[39m [1mYou have enabled experimental feature (serverActions) in next.config.js.[22m
[12:32:52.373] - [33mwarn[39m Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[12:32:52.373] 
[12:32:56.354] Contentlayer config change detected. Updating type definitions and data...
[12:32:56.668] - [35mevent[39m compiled client and server successfully in 1871 ms (20 modules)
[12:32:56.905] - [36mwait[39m compiling...
[12:32:57.148] - [35mevent[39m compiled client and server successfully in 178 ms (20 modules)
[12:32:57.294] Generated 1 documents in .contentlayer

**Comment by alex289** [comment]
The dev command will only start the dev server. In production you should use pnpm build and pnpm start.

**Comment by yoomiraa** [comment]
> The dev command will only start the dev server. In production you should use pnpm build and pnpm start.

Thanks! I'll try it out

**Comment by yoomiraa** [comment]
these errors showed up

[13:24:09.036] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[13:24:09.079] Cloning github.com/yoomiraa/zstvn (Branch: main, Commit: 9b47235)
[13:24:10.976] Cloning completed: 1.897s
[13:24:17.010] Restored build cache
[13:24:17.041] Running "vercel build"
[13:24:17.555] Vercel CLI 31.0.3
[13:24:17.841] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8...
[13:24:17.858] Installing dependencies...
[13:24:18.426] Lockfile is up to date, resolution step is skipped
[13:24:18.526] Progress: resolved 1, reused 0, downloaded 0, added 0
[13:24:18.625] Packages: +54 -49
[13:24:18.625] +++++++++++++++++++++++++++++++++++++++++---------------------------------------
[13:24:19.538] Progress: resolved 54, reused 0, downloaded 8, added 6
[13:24:20.539] Progress: resolved 54, reused 0, downloaded 37, added 28
[13:24:21.539] Progress: resolved 54, reused 0, downloaded 53, added 53
[13:24:22.916] Progress: resolved 54, reused 0, downloaded 54, added 53
[13:24:24.107] Progress: resolved 54, reused 0, downloaded 54, added 54, done
[13:24:24.147] .../node_modules/contentlayer postinstall$ node ./bin/cli.cjs postinstall || echo 'No Contentlayer build found.'
[13:24:25.625] .../node_modules/contentlayer postinstall: Done
[13:24:25.715] 
[13:24:25.727] Done in 7.8s
[13:24:25.750] Detected Next.js version: 13.4.8-canary.5
[13:24:25.751] Running "pnpm build"
[13:24:26.260] 
[13:24:26.260] > @ build /vercel/path0
[13:24:26.260] > npm run setup && next build
[13:24:26.261] 
[13:24:26.643] 
[13:24:26.644] > setup
[13:24:26.644] > node ./lib/setup.mjs
[13:24:26.644] 
[13:24:27.119] - info Loaded env from /vercel/path0/.env
[13:24:27.249] - warn You have enabled experimental feature (serverActions) in next.config.js.
[13:24:27.250] - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[13:24:27.250] 
[13:24:27.340] - info Creating an optimized production build...
[13:24:30.353] Generated 1 documents in .contentlayer
[13:25:13.527] - warn Compiled with warnings
[13:25:13.528] 
[13:25:13.528] ./node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/node.js
[13:25:13.528] Module not found: Can't resolve 'supports-color' in '/vercel/path0/node_modules/.pnpm/debug@4.3.4/node_modules/debug/src'
[13:25:13.528] 
[13:25:13.528] Import trace for requested module:
[13:25:13.528] ./node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/node.js
[13:25:13.528] ./node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/index.js
[13:25:13.528] ./node_modules/.pnpm/https-proxy-agent@5.0.1/node_modules/https-proxy-agent/dist/agent.js
[13:25:13.528] ./node_modules/.pnpm/https-proxy-agent@5.0.1/node_modules/https-proxy-agent/dist/index.js
[13:25:13.529] ./node_modules/.pnpm/gaxios@5.1.2/node_modules/gaxios/build/src/gaxios.js
[13:25:13.529] ./node_modules/.pnpm/gaxios@5.1.2/node_modules/gaxios/build/src/index.js
[13:25:13.529] ./node_modules/.pnpm/google-auth-library@8.8.0/node_modules/google-auth-library/build/src/transporters.js
[13:25:13.529] ./node_modules/.pnpm/google-auth-library@8.8.0/node_modules/google-auth-library/build/src/index.js
[13:25:13.529] ./node_modules/.pnpm/googleapis@118.0.0/node_modules/googleapis/build/src/index.js
[13:25:13.530] ./lib/metrics.tsx
[13:25:13.530] ./app/blog/page.tsx
[13:25:13.530] 
[13:25:13.530] ./node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib/index.js
[13:25:13.530] Module not found: Can't resolve 'encoding' in '/vercel/path0/node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib'
[13:25:13.530] 
[13:25:13.530] Import trace for requested module:
[13:25:13.530] ./node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib/index.js
[13:25:13.531] ./node_modules/.pnpm/gaxios@5.1.2/node_modules/gaxios/build/src/gaxios.js
[13:25:13.531] ./node_modules/.pnpm/gaxios@5.1.2/node_modules/gaxios/build/src/index.js
[13:25:13.534] ./node_modules/.pnpm/google-auth-library@8.8.0/node_modules/google-auth-library/build/src/transporters.js
[13:25:13.534] ./node_modules/.pnpm/google-auth-library@8.8.0/node_modules/google-auth-library/build/src/index.js
[13:25:13.534] ./node_modules/.pnpm/googleapis@118.0.0/node_modules/googleapis/build/src/index.js
[13:25:13.535] ./lib/metrics.tsx
[13:25:13.535] ./app/blog/page.tsx
[13:25:13.535] 
[13:25:13.535] - info Linting and checking validity of types...
[13:25:27.946] - info Collecting page data...
[13:25:28.653] unhandledRejection Error: Cannot find module '../../next@13.4.8-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/constants.js'
[13:25:28.653] Require stack:
[13:25:28.653] - /vercel/path0/.next/server/pages/_document.js
[13:25:28.653] - /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js
[13:25:28.653] - /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js
[13:25:28.654] - /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js
[13:25:28.654] - /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/worker.js
[13:25:28.654] - /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js
[13:25:28.654]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[13:25:28.654]     at /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:189:36
[13:25:28.654]     at Module._load (node:internal/modules/cjs/loader:922:27)
[13:25:28.654]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[13:25:28.654]     at require (node:internal/modules/cjs/helpers:110:18)
[13:25:28.654]     at 85511 (/vercel/path0/.next/server/pages/_document.js:32:18)
[13:25:28.654]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[13:25:28.654]     at 83520 (/vercel/path0/.next/server/chunks/520.js:41:20)
[13:25:28.654]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[13:25:28.654]     at __webpack_exec__ (/vercel/path0/.next/server/pages/_document.js:63:39) {
[13:25:28.654]   type: 'Error',
[13:25:28.654]   code: 'MODULE_NOT_FOUND',
[13:25:28.654]   requireStack: [
[13:25:28.654]     '/vercel/path0/.next/server/pages/_document.js',
[13:25:28.654]     '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js',
[13:25:28.654]     '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js',
[13:25:28.654]     '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js',
[13:25:28.654]     '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/worker.js',
[13:25:28.654]     '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js'
[13:25:28.655]   ]
[13:25:28.655] }
[13:25:28.833]  ELIFECYCLE  Command failed with exit code 1.
[13:25:28.863] Error: Command "pnpm build" exited with 1

**Comment by alex289** [comment]
Thats odd. Seems like something with the installed node_modules id broken

**Comment by yoomiraa** [comment]
> Thats odd. Seems like something with the installed node_modules id broken

Maybe I'll just wait until problem is solved. 
*ps: I'm using vercel to run it

**Comment by yoomiraa** [comment]
> I'm
> 
> > these errors showed up
> > [13:24:09.036] Running build in Washington, D.C., USA (East) – iad1 (Hive) [13:24:09.079] Cloning github.com/yoomiraa/zstvn (Branch: main, Commit: 9b47235) [13:24:10.976] Cloning completed: 1.897s [13:24:17.010] Restored build cache [13:24:17.041] Running "vercel build" [13:24:17.555] Vercel CLI 31.0.3 [13:24:17.841] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8... [13:24:17.858] Installing dependencies... [13:24:18.426] Lockfile is up to date, resolution step is skipped [13:24:18.526] Progress: resolved 1, reused 0, downloaded 0, added 0 [13:24:18.625] Packages: +54 -49 [13:24:18.625] +++++++++++++++++++++++++++++++++++++++++--------------------------------------- [13:24:19.538] Progress: resolved 54, reused 0, downloaded 8, added 6 [13:24:20.539] Progress: resolved 54, reused 0, downloaded 37, added 28 [13:24:21.539] Progress: resolved 54, reused 0, downloaded 53, added 53 [13:24:22.916] Progress: resolved 54, reused 0, downloaded 54, added 53 [13:24:24.107] Progress: resolved 54, reused 0, downloaded 54, added 54, done [13:24:24.147] .../node_modules/contentlayer postinstall$ node ./bin/cli.cjs postinstall || echo 'No Contentlayer build found.' [13:24:25.625] .../node_modules/contentlayer postinstall: Done [13:24:25.715] [13:24:25.727] Done in 7.8s [13:24:25.750] Detected Next.js version: 13.4.8-canary.5 [13:24:25.751] Running "pnpm build" [13:24:26.260] [13:24:26.260] > @ build /vercel/path0 [13:24:26.260] > npm run setup && next build [13:24:26.261] [13:24:26.643] [13:24:26.644] > setup [13:24:26.644] > node ./lib/setup.mjs [13:24:26.644] [13:24:27.119] - info Loaded env from /vercel/path0/.env [13:24:27.249] - warn You have enabled experimental feature (serverActions) in next.config.js. [13:24:27.250] - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk. [13:24:27.250] [13:24:27.340] - info Creating an optimized production build... [13:24:30.353] Generated 1 documents in .contentlayer [13:25:13.527] - warn Compiled with warnings [13:25:13.528] [13:25:13.528] ./node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/node.js [13:25:13.528] Module not found: Can't resolve 'supports-color' in '/vercel/path0/node_modules/.pnpm/debug@4.3.4/node_modules/debug/src' [13:25:13.528] [13:25:13.528] Import trace for requested module: [13:25:13.528] ./node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/node.js [13:25:13.528] ./node_modules/.pnpm/debug@4.3.4/node_modules/debug/src/index.js [13:25:13.528] ./node_modules/.pnpm/https-proxy-agent@5.0.1/node_modules/https-proxy-agent/dist/agent.js [13:25:13.528] ./node_modules/.pnpm/https-proxy-agent@5.0.1/node_modules/https-proxy-agent/dist/index.js [13:25:13.529] ./node_modules/.pnpm/gaxios@5.1.2/node_modules/gaxios/build/src/gaxios.js [13:25:13.529] ./node_modules/.pnpm/gaxios@5.1.2/node_modules/gaxios/build/src/index.js [13:25:13.529] ./node_modules/.pnpm/google-auth-library@8.8.0/node_modules/google-auth-library/build/src/transporters.js [13:25:13.529] ./node_modules/.pnpm/google-auth-library@8.8.0/node_modules/google-auth-library/build/src/index.js [13:25:13.529] ./node_modules/.pnpm/googleapis@118.0.0/node_modules/googleapis/build/src/index.js [13:25:13.530] ./lib/metrics.tsx [13:25:13.530] ./app/blog/page.tsx [13:25:13.530] [13:25:13.530] ./node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib/index.js [13:25:13.530] Module not found: Can't resolve 'encoding' in '/vercel/path0/node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib' [13:25:13.530] [13:25:13.530] Import trace for requested module: [13:25:13.530] ./node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib/index.js [13:25:13.531] ./node_modules/.pnpm/gaxios@5.1.2/node_modules/gaxios/build/src/gaxios.js [13:25:13.531] ./node_modules/.pnpm/gaxios@5.1.2/node_modules/gaxios/build/src/index.js [13:25:13.534] ./node_modules/.pnpm/google-auth-library@8.8.0/node_modules/google-auth-library/build/src/transporters.js [13:25:13.534] ./node_modules/.pnpm/google-auth-library@8.8.0/node_modules/google-auth-library/build/src/index.js [13:25:13.534] ./node_modules/.pnpm/googleapis@118.0.0/node_modules/googleapis/build/src/index.js [13:25:13.535] ./lib/metrics.tsx [13:25:13.535] ./app/blog/page.tsx [13:25:13.535] [13:25:13.535] - info Linting and checking validity of types... [13:25:27.946] - info Collecting page data... [13:25:28.653] unhandledRejection Error: Cannot find module '../../[next@13.4.8-canary.5_biqbaboplfbrettd7655fr4n2y](mailto:next@13.4.8-canary.5_biqbaboplfbrettd7655fr4n2y)/node_modules/next/dist/shared/lib/constants.js' [13:25:28.653] Require stack: [13:25:28.653] - /vercel/path0/.next/server/pages/_document.js [13:25:28.653] - /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js [13:25:28.653] - /vercel/path0/node_modules/.pnpm/next@[13.4.8-canary.5_@opentelemetry](mailto:13.4.8-canary.5_@opentelemetry)+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js [13:25:28.654] - /vercel/path0/node_modules/.pnpm/next@[13.4.8-canary.5_@opentelemetry](mailto:13.4.8-canary.5_@opentelemetry)+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js [13:25:28.654] - /vercel/path0/node_modules/.pnpm/next@[13.4.8-canary.5_@opentelemetry](mailto:13.4.8-canary.5_@opentelemetry)+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/worker.js [13:25:28.654] - /vercel/path0/node_modules/.pnpm/next@[13.4.8-canary.5_@opentelemetry](mailto:13.4.8-canary.5_@opentelemetry)+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js [13:25:28.654] at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15) [13:25:28.654] at /vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:189:36 [13:25:28.654] at Module._load (node:internal/modules/cjs/loader:922:27) [13:25:28.654] at Module.require (node:internal/modules/cjs/loader:1143:19) [13:25:28.654] at require (node:internal/modules/cjs/helpers:110:18) [13:25:28.654] at 85511 (/vercel/path0/.next/server/pages/_document.js:32:18) [13:25:28.654] at **webpack_require** (/vercel/path0/.next/server/webpack-runtime.js:25:43) [13:25:28.654] at 83520 (/vercel/path0/.next/server/chunks/520.js:41:20) [13:25:28.654] at **webpack_require** (/vercel/path0/.next/server/webpack-runtime.js:25:43) [13:25:28.654] at **webpack_exec** (/vercel/path0/.next/server/pages/_document.js:63:39) { [13:25:28.654] type: 'Error', [13:25:28.654] code: 'MODULE_NOT_FOUND', [13:25:28.654] requireStack: [ [13:25:28.654] '/vercel/path0/.next/server/pages/_document.js', [13:25:28.654] '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js', [13:25:28.654] '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js', [13:25:28.654] '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js', [13:25:28.654] '/vercel/path0/node_modules/.pnpm/next@13.4.8-canary.5_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/worker.js', [13:25:28.654] '/vercel/path0/node_modules/.pnpm/next@[13.4.8-canary.5_@opentelemetry](mailto:13.4.8-canary.5_@opentelemetry)+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js' [13:25:28.655] ] [13:25:28.655] } [13:25:28.833]  ELIFECYCLE  Command failed with exit code 1. [13:25:28.863] Error: Command "pnpm build" exited with 1
> 
> This is an error with the latest contentlayer. (0.3.2-0.3.4) I used a trick to bypass this issue. Which is kinda weird. Just make any changes like fixing a typo. (redeployment won't work). Hope it works for you.

Thanks for the help!
