### ISSUE TITLE
VercelPostgresError: VercelPostgresError - 'invalid_connection_string':

### ISSUE THREAD

**Issue by mustafakhokhar** [leerob/leerob.io#671]
I have filled out the .env file with connection strings from supabase but still unable to run it locally.

<img width="261" alt="Screenshot 2023-11-23 at 4 49 48 PM" src="https://github.com/leerob/leerob.io/assets/36676309/ca8544e7-9d29-4970-a8bd-aaf014e6839a">

Complete trace:
```
VercelPostgresError: VercelPostgresError - 'invalid_connection_string': This connection string is meant to be used with a direct connection. Make sure to use a pooled connection string or try `createClient()` instead.
    at createPool (file:///Users/mustafakhokhar/Documents/GitHub/leerob.io/node_modules/.pnpm/@vercel+postgres@0.5.1/node_modules/@vercel/postgres/dist/chunk-VGUHM5WG.js:163:11)
    at Object.apply (file:///Users/mustafakhokhar/Documents/GitHub/leerob.io/node_modules/.pnpm/@vercel+postgres@0.5.1/node_modules/@vercel/postgres/dist/chunk-VGUHM5WG.js:211:16)
    at Object.redirects (file:///Users/mustafakhokhar/Documents/GitHub/leerob.io/next.config.mjs:8:42)
    at loadRedirects (/Users/mustafakhokhar/Documents/GitHub/leerob.io/node_modules/.pnpm/next@14.0.4-canary.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/lib/load-custom-routes.js:360:34)
    at loadCustomRoutes (/Users/mustafakhokhar/Documents/GitHub/leerob.io/node_modules/.pnpm/next@14.0.4-canary.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/lib/load-custom-routes.js:438:9)
    at setupFsCheck (/Users/mustafakhokhar/Documents/GitHub/leerob.io/node_modules/.pnpm/next@14.0.4-canary.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-utils/filesystem.js:238:60)
    at initialize (/Users/mustafakhokhar/Documents/GitHub/leerob.io/node_modules/.pnpm/next@14.0.4-canary.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:54:58)
    at async Server.<anonymous> (/Users/mustafakhokhar/Documents/GitHub/leerob.io/node_modules/.pnpm/next@14.0.4-canary.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:237:36) {
  code: 'invalid_connection_string'
}
```

**Comment by leerob** [comment]
Hey! This repo is using Vercel Postgres. You'll need to make some changes to use Supabase.
